<a href="https://colab.research.google.com/github/hkyoo52/Algorithm/blob/main/%EC%B5%9C%EB%8B%A8%EA%B2%BD%EB%A1%9C%2C_%EA%B7%B8%EB%9E%98%ED%94%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **최단경로**

### **개선된 다익스트라 알고리즘 코드**

In [ ]:
n,m=6,11
graph=[[]for i in range(n+1)]
for _ in range(m):
  a,b,c=map(int,input().split())
  graph[a].append((b,c))

1 2 2
1 3 5
1 4 1
2 3 3
2 4 2
3 2 3
3 6 5
4 3 3
4 5 1
5 3 1
5 6 2


In [ ]:
distance=[int(1e9)] * (n+1)

In [ ]:
import heapq
import sys

def dijkstra(start):
  q=[]
  heapq.heappush(q,(0,start))
  distance[start]=0
  while q:
    dist,now=heapq.heappop(q)
    if distance[now]<dist:
      continue
    for i in graph[now]:
      cost=dist+i[1]
      if cost<distance[i[0]]:
        distance[i[0]]=cost
        heapq.heappush(q,(cost,i[0]))
  return distance

In [ ]:
dis=dijkstra(1)
for i in range(1,len(dis)):
  if dis[i]==int(1e9):
    print('무한')
  else:
    print(dis[i])


0
2
3
1
2
4


### **미래 도시**

In [ ]:
import copy

INF=int(1e9)

n,m=map(int,input().split())
graph=[[] for i in range(n+1)]
distance=[INF]*(n+1)
x,k=map(int,input().split())

for _ in range(m):
  a,b=map(int,input().split())
  graph[a].append(b)

c_graph=copy.deepcopy(graph)
for i in range(len(graph)):
  for j in c_graph[i]:
    graph[j].append(i)

for i in graph:
  for j in i:
    graph[j].append(i)

def dijkstra(start,end):
  distance[start]=0
  for i in range(1,5+1):
    for j in graph[i]:
      distance[j]=min(distance[j],distance[i]+1)
  return distance[end]

print(dijkstra(1,X)+dijkstra(X,K))

ValueError: ignored

In [ ]:
graph=[[],[2,3,4],[4],[4,5],[5],[]]
distance=[INF]*(n+1)

c_graph=copy.deepcopy(graph)

for i in range(len(graph)):
  for j in c_graph[i]:
    graph[j].append(i)

def dijkstra(start,end):
  distance[start]=0
  for i in range(1,5+1):
    for j in graph[i]:
      distance[j]=min(distance[j],distance[i]+1)
  return distance[end]

print(dijkstra(1,5)+dijkstra(5,4))

3


### **플로이드**

In [ ]:
import numpy as np
def flowed(n,arr):
  INF=int(1e9)
  graph=[[INF]*(n+1) for _ in range(n+1)]
  for i in range(1,n+1):
    graph[i][i]=0
  for j in arr:
    graph[j[0]][j[1]]=min(j[2],graph[j[0]][j[1]])

  for k in range(1,n+1):
    for a in range(1,n+1):
      for b in range(1,n+1):
        graph[a][b]=min(graph[a][b],graph[a][k]+graph[k][b])

  for i in range(1,n+1):
    for j in range(1,n+1):
      if graph[i][j]==INF:
        graph[i][j]='INF'
  return np.array(graph)[1:,1:]

In [ ]:
n=5
arr=[[1,2,2],[1,3,3],[1,4,1],[1,5,10],[2,4,2],[3,4,1],[3,5,1],[4,5,3],[3,5,10],[3,1,8],[1,4,2],[5,1,7],[3,4,2],[5,2,4]]
graph=flowed(n,arr)
for i in graph:
  print(i)

[0 2 3 1 4]
[12  0 15  2  5]
[8 5 0 1 1]
[10  7 13  0  3]
[ 7  4 10  6  0]


### **정확한 순위**

In [ ]:
import numpy as np
INF=int(1e9)
def score(arr,n):
  graph=[[INF]*(n+1) for _ in range(n+1)]
  for i in range(1,n+1):
    graph[i][i]=0
  for j in arr:
    graph[j[0]][j[1]]=1
    graph[j[1]][j[0]]=-1

  for a in range(1,n+1):
    for b in range(1,n+1):
      for k in range(1,n+1):
        if graph[a][b]==1 and graph[b][k]==1:
          graph[a][k]=1
        elif graph[a][b]==-1 and graph[b][k]==-1:
          graph[a][k]=-1

  graph=np.array(graph)[1:,1:]

  count=0
  for i in graph:
    if INF not in i:
      count+=1
  return count

In [ ]:
n=6
arr=[[1,5],[3,4],[4,2],[4,6],[5,2],[5,4]]
score(arr,n)

1

### **화성 탐사**

In [ ]:
#bfs
from collections import deque
INF=int(1e9)
def travel(arr):
  n=len(arr)
  graph=[[INF]*(n) for _ in range(n)]
  graph[0][0]=arr[0][0]
  queue=deque()
  queue.append([0,0])
  dr=[1,0,0,-1]
  dc=[0,1,-1,0]
  while queue:
    r,c=queue.popleft()
    for i in range(4):
      nr,nc=r+dr[i],c+dc[i]
      if 0<=nc<len(arr) and 0<=nr<len(arr[0]):
        if arr[nr][nc]+graph[r][c]<graph[nr][nc]:
          graph[nr][nc]=graph[r][c]+arr[nr][nc]
          queue.append([nr,nc])
    
  return graph[n-1][n-1]

In [ ]:
arr=[[5,5,4],
     [3,9,1],
     [3,2,7]]
travel(arr)

20

In [ ]:
arr=[[3,7,2,0,1],[2,8,0,9,1],[1,2,1,8,1],[9,8,9,2,0],[3,6,5,1,5]]
travel(arr)

19

In [ ]:
import heapq
def dijkstra(arr):
  q=[]
  n=len(arr)
  heapq.heappush(q,(arr[0][0],[0,0]))
  graph=[[INF]*(n) for _ in range(n)]
  graph[0][0]=arr[0][0]
  dr=[1,0,0,-1]
  dc=[0,1,-1,0]
  while q:
    dist,now=heapq.heappop(q)
    r,c=now
    if graph[r][c]<dist:
      continue
    for i in range(4):
      nr,nc=r+dr[i],c+dc[i]
      if 0<=nc<len(arr) and 0<=nr<len(arr[0]):
        cost=dist+arr[nr][nc]
        if cost<graph[nr][nc]:
          graph[nr][nc]=cost
          heapq.heappush(q,(cost,[nr,nc]))
  return graph[n-1][n-1]


In [ ]:
arr=[[3,7,2,0,1],[2,8,0,9,1],[1,2,1,8,1],[9,8,9,2,0],[3,6,5,1,5]]
dijkstra(arr)

19

### **숨바꼭질**

In [ ]:
import heapq
def find(n,arr):
  INF=int(1e9)
  distance=[INF for _ in range(n+1)]
  distance[1]=0
  graph=[[] for _ in range(n+1)]
  for i in arr:
    graph[i[0]].append(i[1])
    graph[i[1]].append(i[0])

  q=[]
  heapq.heappush(q,(0,1))

  while q:
    dist,now=heapq.heappop(q)
    if distance[now]<dist:
      continue
    for i in graph[now]:
      if dist+1<distance[i]:
        distance[i]=dist+1
        heapq.heappush(q,(dist+1,i))

  distance=distance[1:]
  ind=distance.index(max(distance))
  count=distance.count(max(distance))
  return ind+1,distance[ind],count

In [ ]:
arr=[[3,6],[4,3],[3,2],[1,3],[1,2],[2,4],[5,2]]
find(6,arr)

[1000000000, 0, 1, 1, 2, 2, 2]


(4, 2, 3)

## **그래프 이론**

### **서로소**

In [ ]:
#현재 값의 value를 parent값으로 만듬
def find_parent(parent,x):
  if parent[x] !=x:
    return find_parent(parent,parent[x])
  return x


#2개의 값을 연결하기(한쪽을 부모로)
def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a<b:
    parent[b]=a
  else:
    parent[a]=b

In [ ]:
v,e=6,4
parent=[i for i in range(v+1)]
arr=[[1,4],[2,3],[2,4],[5,6]]
for i in arr:
  union_parent(parent,i[0],i[1])
print(parent)

[0, 1, 1, 2, 1, 5, 5]


In [ ]:
 def find_parent(parent,x):
  if parent[x] !=x:
    return find_parent(parent,parent[x])
  return x

  
def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a<b:
    parent[b]=a
  else:
    parent[a]=b

In [ ]:
v,e=3,3
parent=[i for i in range(v+1)]

cycle=False

arr=[[1,2],[1,3],[2,3]]
for i in arr:
  if find_parent(parent,i[0])==find_parent(parent,i[1]):
    cycle=True
    break
  else:
    union_parent(parent,i[0],i[1])
if cycle:
  print('cycle')
else:
  print('not cycle')

cycle


### **크루스칼 알고리즘**

In [ ]:
def find_parent(parent,x):
  if parent[x] != x:
    find_parent(parent,parent[x])
  return parent[x]

def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a>b:
    parent[a]=b
  else:
    parent[b]=a



In [ ]:
v,e=7,9
arr=[[1,2,29],[1,5,75],[2,3,35],[2,6,34],[3,4,7],[4,6,23],[4,7,13],[5,6,53],[6,7,25]]
arr=sorted(arr,key=lambda x : x[2])
parent=[i for i in range(v+1)]
sum=0
for i in arr:
  if find_parent(parent,i[0]) == find_parent(parent,i[1]):
    continue
  else:
    sum+=i[2]
    union_parent(parent,i[0],i[1])

print(sum)

159


### **위상정렬**

In [ ]:
from collections import deque

def change(arr,v):
  graph=[[] for i in range(v+1)]
  indegree=[0]*(v+1)
  for i in arr:
    graph[i[0]].append(i[1])
    indegree[i[1]]=indegree[i[1]]+1

  return graph, indegree

def topology_sort(graph,indegree):
  result=[]
  q=deque()
  for i in range(1,v+1):
    if indegree[i]==0:
      q.append(i)
  while q:
    now=q.popleft()
    result.append(now)
    for i in graph[now]:
      indegree[i]-=1
      if indegree[i]==0:
        q.append(i)
  return result

In [ ]:
v,e=7,8
arr=[[1,2],[1,5],[2,3],[2,6],[3,4],[4,7],[5,6],[6,4]]
graph,indegree=change(arr,v)
topology_sort(graph,indegree)

[1, 2, 5, 3, 6, 4, 7]

### **팀 결성**

In [ ]:
class make_team:
  def __init__(self,team_arr,do_arr):
    self.team_arr=team_arr
    self.do_arr=do_arr

  def find_parent(self,n):
    if self.team_arr[n] != n:
      find_parent(self.team_arr,self.team_arr[n])
    return self.team_arr[n]

  def same_team(self,n1,n2):
    n1=self.find_parent(n1)
    n2=self.find_parent(n2)
    if n1>n2:
      self.team_arr[n1]=n2
    else:
      self.team_arr[n2]=n1
    return team_arr

  def check_team(self,n1,n2):
    n1=find_parent(self.team_arr,n1)
    n2=find_parent(self.team_arr,n2)
    if n1==n2:
      print('YES')
    else:
      print('NO')

  def do(self):
    for i in self.do_arr:
      if i[0]==0:
        self.team_arr=self.same_team(i[1],i[2])
      else:
        self.check_team(i[1],i[2])

In [ ]:
N=7
team_arr=[i for i in range(N+1)]
do_arr=[[0,1,3],[1,1,7],[0,7,6],[1,7,1],[0,3,7],[0,4,2],[0,1,1],[1,1,1]]
team=make_team(team_arr,do_arr)
team.do()

NO
NO
YES


### **도시 분할 계획**

In [ ]:
def find_parent(parent,x):
  if parent[x] != x:
    return find_parent(parent,parent[x])
  return parent[x]

def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a>b:
    parent[a]=b
  else:
    parent[b]=a

def get_fee(arr,v):
  arr=sorted(arr,key=lambda x:x[2])
  parent=[i for i in range(v+1)]
  sum_arr=[]
  for i in arr:
    if find_parent(parent,i[0]) == find_parent(parent,i[1]):
      continue
    else:
      sum_arr.append(i[2])
      union_parent(parent,i[0],i[1])
  sum_arr=sorted(sum_arr)[:-1]
  return sum(sum_arr)

In [ ]:
v,e=7,12
arr=[[1,2,3],[1,3,2],[3,2,1],[2,5,2],[3,4,4],[7,3,6],[5,1,5],[1,6,2],[6,4,1],[6,5,3],[4,5,3],[6,7,4]]
get_fee(arr,v)

8

### **커리큘럼**

In [ ]:
from collections import deque
def all_time(graph,n):
  time=[[0] for _ in range(n+1)]
  q=deque()
  for i in range(len(graph)):
    if len(graph[i])==1:
      time[i]=graph[i][0]
      q.append(i)
  while q:
    now=q.popleft()
    for i in range(len(graph)):
      if len(graph[i])>=2 and now in graph[i][1:]:
        if len(graph[i])==2:
          time[i]=max(time[now]+graph[i][0],time[i][0])
          q.append(i)
        else:
          ind=graph[i][1:].index(now)
          del graph[i][now+1]
  return time[1:]

    

In [ ]:
n=5
graph=[[],[10],[10,1],[4,1],[4,3,1],[3,3]]

all_time(graph,n)

[10, 20, 14, 18, 17]

### **여행 계획**

In [ ]:
def find_parent(parent,x):
  if parent[x]!=x:
    return find_parent(parent,parent[x])
  return parent[x]

In [ ]:
def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a>b:
    parent[a]=b
  else:
    parent[b]=a

In [ ]:
def can_do(graph,arr):
  arr=[i-1 for i in arr]
  parent=[i for i in range(len(graph))]
  for i in range(len(graph)):
    for j in range(len(graph[0])):
      if graph[i][j]==1:
        union_parent(parent,i,j)

  for i in range(len(arr)-1):
    if find_parent(parent,arr[i])==find_parent(parent,arr[i+1]):
      pass
    else:
      return 'N0'
  return 'YES'


In [ ]:
graph=[[0,1,0,1,1],[1,0,1,1,0],[0,1,0,0,0],[1,1,0,0,0],[1,0,0,0,0]]
arr=[2,3,4,3]
can_do(graph,arr)

'YES'

### **탑승구**

In [ ]:
def get_max(chair,n):
  if chair[n] ==0:
    chair[n]=1
  else:
    return get_max(chair,n-1)

In [ ]:
def count(G,arr):
  chair = [0 for i in range(G+1)]
  for i in range(len(arr)):
    get_max(chair,arr[i])
    if chair[0]==1:
      return i

In [ ]:
G=4
arr=[4,1,1]
count(G,arr)

2

In [ ]:
G=4
arr=[2,2,3,3,4,5]
count(G,arr)

3

### **어두운 길**

In [ ]:
def find_parent(parent,x):
  if parent[x]!=x:
    return find_parent(parent,parent[x])
  return parent[x]

def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a>b:
    parent[a]=b
  else:
    parent[b]=a

In [ ]:
def dark_road(arr,N):
  parent=[i for i in range(N+1)]
  arr=sorted(arr,key = lambda x : x[2])
  sum=0
  for i in arr:
    if find_parent(parent,i[0]) != find_parent(parent,i[1]):
      union_parent(parent,i[0],i[1])
    else:
      sum+=i[2]
  return sum

In [ ]:
N=7
arr=[[0,1,7],[0,3,5],[1,2,8],[1,3,9],[1,4,7],[2,4,5],[3,4,15],[3,5,6],[4,5,8],[4,6,9],[5,6,11]]
dark_road(arr,N)

51

### **행성터널**

In [ ]:
import numpy as np
def loss_func(arr1,arr2):
  return min(abs(np.array(arr1)-np.array(arr2)))

def find_parent(parent,x):
  if parent[x]!=x:
    return find_parent(parent,parent[x])
  return parent[x]

def union_parent(parent,a,b):
  a=find_parent(parent,a)
  b=find_parent(parent,b)
  if a>b:
    parent[a]=b
  else:
    parent[b]=a

In [ ]:
import itertools
def turnel(arr):
  graph=[]
  parent=[x for x in range(len(arr)+1)]
  arr_case=itertools.combinations([i for i in range(len(arr))], 2)

  for i in arr_case:
    #[[1,2, 비용],[1,3,비용].....]
    lis=[i[0],i[1],loss_func(arr[i[0]],arr[i[1]])]
    graph.append(lis)
  graph=sorted(graph,key = lambda x : x[2])
  sum=0
  for i in graph:
    if find_parent(parent,i[0]) != find_parent(parent,i[1]):
      union_parent(parent,i[0],i[1])
      sum+=i[2]
  return sum


In [ ]:
arr=[[11,-15,-15],[14,-5,-15],[-1,-1,-5],[10,-4,-1],[19,-4,19]]
turnel(arr)

0.005782365798950195


4

### **최종 순위**

In [ ]:
def last_lanking(last, change):
  for i in range(len(last)-1):
    if [last[i+1],last[i]] in change:
      change.remove([last[i+1],last[i]])
      last[i],last[i+1]=last[i+1],last[i]
  if len(change) != 0:
    for i in change:
      if last.index(i[0]) > last.index(i[1]):
        return '?'
      else:
        break
    return 'IMPOSSIBLE'
  else:
    return last 

In [ ]:
last=[5,4,3,2,1]
change=[[2,4],[3,4]]
last_lanking(last,change)

[5, 3, 2, 4, 1]

In [ ]:
last=[2,3,1]
change=[]
last_lanking(last,change)

[2, 3, 1]

In [ ]:
last=[1,2,3,4]
change=[[1,2],[3,4],[2,3]]
last_lanking(last,change)

'IMPOSSIBLE'